codex-storage/codex-contracts-eth

- .gitignore
- Readme.md
- contracts/Storage.sol
- contracts/TestToken.sol
- deploy/storage.js
- deploy/token.js
- deployments/.gitignore
- hardhat.config.js
- package-lock.json
- package.json
- test/Stakes.test.js
- test/Storage.test.js
* Adds [hardhat-deploy](https://github.com/wighawag/hardhat-deploy) plugin.
* Adds a deployment script for the Storage contract.
* Adds a `npm start` command that starts a development node with the Storage contract already deployed.
> Deployment

- .prettierrc
- .solhint.json
- contracts/Contracts.sol
- contracts/Proofs.sol
- contracts/Stakes.sol
- contracts/Storage.sol
- contracts/TestContracts.sol
- contracts/TestProofs.sol
- contracts/TestStakes.sol
- contracts/TestToken.sol
- deploy/storage.js
- deploy/token.js
- package-lock.json
- package.json
- test/Contracts.test.js
- test/Proofs.test.js
- test/Stakes.test.js
- test/Storage.test.js
- test/examples.js
- test/marketplace.js
Added [solhint](https://github.com/protofire/solhint) and [prettier](https://prettier.io/), to ensure consistent formatting and enable styling and security warnings.
> Linter and formatter

- contracts/Marketplace.sol
- contracts/Periods.sol
- contracts/Proofs.sol
- contracts/TestProofs.sol
Extracts the logic from `Proofs` that deals with time periods into `Periods.sol`.
> Introduce abstraction for dealing with time periods

- contracts/Marketplace.sol
- contracts/Requests.sol
- contracts/StateRetrieval.sol
Moves implementation of `myRequests()` and `mySlots()` out of `Marketplace.sol` into a separate file.
> Extract myRequests() and mySlots()

- .solhint.json
- contracts/Collateral.sol
- contracts/Configuration.sol
- contracts/Marketplace.sol
- contracts/Periods.sol
- contracts/Proofs.sol
- contracts/Requests.sol
- contracts/StateRetrieval.sol
- contracts/TestCollateral.sol
- contracts/TestMarketplace.sol
- contracts/TestProofs.sol
- deploy/marketplace.js
- test/Marketplace.test.js
- test/Proofs.test.js
- test/examples.js
- test/marketplace.js
- test/requests.js
- replaces variables and functions related to slot state with an explicit `SlotState` enum
- replaces several configuration variables and getters with a single `MarketplaceConfiguration` struct
- many small cleaning commits
> Introduce SlotState

- contracts/Proofs.sol
- package-lock.json
- package.json
- test/Proofs.test.js
* fixes the case where the probability is 1 (proofs always required)
* uses a binomial test to check probabilities (more reliable unit test)
> Fix proof probability

- contracts/Configuration.sol
- contracts/Marketplace.sol
- contracts/Requests.sol
- deploy/marketplace.js
- package.json
- test/Marketplace.test.js
- test/examples.js
Closes #46 
Also does a bit of space optimization on the used numeric types for the config values.
> feat: collateral fractions

- deploy/token.js
This PR adds funding of the TestToken to development accounts
> build: funds localhost env. accounts

- deploy/token.js
- docker/deploy.Dockerfile
- docker/deploy.sh
- hardhat.config.js
- package.json
Adds a docker image that allows deployment of the smart contracts.
> Deploy contracts using docker

- contracts/Marketplace.sol
- test/Marketplace.test.js
1. add request expiry to StorageRequested evcent
2. add slotIndex to SlotFreed event
3. remove slotIndex as an indexed emission of SlotFIlled event
4. copy slotIndex before deleting slot, as it was emitting 0!
> Support slot queue

- .github/workflows/docker.yml
These changes just to align with similar changes we introduced in [nim-codex docker workflow](https://github.com/codex-storage/nim-codex/pull/474)
- Build an push in same step
- Remove minify step
```
linux/amd64: 162.20 MB --> 162.21 MB
linux/arm64: 162.42 MB --> 162.42 MB
```
> Update Docker workflow

- contracts/Marketplace.sol
- contracts/Requests.sol
- test/Marketplace.test.js
- test/Proofs.test.js
- test/evm.js
- test/marketplace.js
- test/requests.js
> feat: partial payouts for cancelled requests

- deploy/marketplace.js
> Fix deployment bug in loading zkey hash

- contracts/Proofs.sol
As part of work on defining Application Properties for Certora you can find here: https://notes.status.im/s/D29-EqKzi
I have been writing comments in the code to explain the code's functionality better.
> docs: proofs comments

- certora/confs/Marketplace.conf
- certora/harness/MarketplaceHarness.sol
- certora/specs/Marketplace.spec
- contracts/Marketplace.sol
This commit adds CVL rule that formally verifies the state changes of
any given request in relation to the functions of the contract that can
cause them.
Closes #128
> chore: formally verify request state changes

- certora/specs/Marketplace.spec
This invariant ensures that the total supply of the used token in the contract is always greater equal to the sum of all balances within the token combined.
**This PR depends on #142**
> chore(certora): add invariant that totalSupply is sumOfBalances

- contracts/Configuration.sol
- contracts/FuzzMarketplace.sol
- contracts/Proofs.sol
- deploy/marketplace.js
- test/Proofs.test.js
- test/examples.js
> chore: add `downtimeProduct` configuration parameter

- certora/specs/Marketplace.spec
This adds a rule to formally verify that the `SlotState` and `RequestState` of any given `Slot` or `Request` does not change more than once per function call.
Closes #129
> chore(certora): verify SlotState and RequestState changes count

- certora/specs/Marketplace.spec
The prover found a counter example where it starts with a request that has an id `0`, which always results in a `SlotState.New`, resulting in that request becoming `RequestState.Started` while it should be `RequestState.Cancelled`.
We're fixing this by requiring that when the `requestId == 0` then the slot's client has to be `0` address as well.
This will cause a reverting case in the prover, preventing it to find a false positive.
> fix(certora): fix failing rule that cancelled requests stay cancelled

- certora/specs/Marketplace.spec
This PR adds some check on slot state transitions and verifies that once a slot has been paid, it can be freed and paid again. 
closes: #126 
Certora run https://prover.certora.com/output/27938/d4ff657fb4974c48b12218b53d7153f4?anonymousKey=687b8641dd3f0b818531a1198cee6e82273dd76f
> chore(certora): verify slots transitions and that a slot can be paid only once

- .github/workflows/ci.yml
- certora/confs/StateChanges.conf
- certora/specs/Marketplace.spec
- certora/specs/StateChanges.spec
- certora/specs/shared.spec
- package.json
> refactor(certora): extract `allowedRequestStateChanges` rule into own

- configuration/configuration.js
- configuration/networks/hardhat/configuration.js
- deploy/marketplace.js
By default we now have a proof period of 2 minutes, but on hardhat it's still 1 minute.
> Different proof periods for different networks

- contracts/Proofs.sol
- test/Proofs.test.js
> Reject when probability is 0

- contracts/Marketplace.sol
- test/Marketplace.test.js
> Add request validations

- contracts/Marketplace.sol
- contracts/Requests.sol
- deploy/token.js
- test/Marketplace.test.js
- test/collateral.js
- test/examples.js
- test/ids.js
- test/marketplace.js
- test/price.js
> This PR is one of the PRs for issue https://github.com/codex-storage/nim-codex/issues/460. See https://github.com/codex-storage/nim-codex/issues/460#issuecomment-2583250768.
Here we do the following:
1. changes `ask.reward` to `ask.pricePerByte`
2. changes `ask.collateral` to `ask.collateralPerByte`
3. updates all related computations and tests
> Feat: price per byte

- configuration/configuration.js
- configuration/networks/hardhat/configuration.js
- contracts/Configuration.sol
- contracts/FuzzMarketplace.sol
- contracts/Marketplace.sol
- test/Marketplace.test.js
- test/examples.js
> Remove missing proof leniency

- configuration/configuration.js
- configuration/networks/hardhat/configuration.js
- contracts/Configuration.sol
- contracts/FuzzMarketplace.sol
- contracts/Marketplace.sol
- test/Marketplace.test.js
- test/examples.js
Closes https://github.com/codex-storage/codex-contracts-eth/issues/101
Implements 30 days limit.
> feat: request duration limit

- .github/workflows/ci.yml
- .solhint.json
- certora/harness/MarketplaceHarness.sol
- certora/helpers/ERC20A.sol
- contracts/Configuration.sol
- contracts/Endian.sol
- contracts/FuzzMarketplace.sol
- contracts/Groth16.sol
- contracts/Groth16Verifier.sol
- contracts/Marketplace.sol
- contracts/Periods.sol
- contracts/Proofs.sol
- contracts/Requests.sol
- contracts/SlotReservations.sol
- contracts/StateRetrieval.sol
- contracts/TestEndian.sol
- contracts/TestMarketplace.sol
- contracts/TestProofs.sol
- contracts/TestSlotReservations.sol
- contracts/TestToken.sol
- contracts/TestVerifier.sol
- hardhat.config.js
- package-lock.json
- package.json
Also updates `solhint` and `prettier` to deal with the updated language constructs, such as user defined operators.
Requires #218 to be merged first.
> Update solidity version

- contracts/Marketplace.sol
- test/Marketplace.test.js
> fix: only slots host should be able to submit proof
