contracts/Marketplace.sol
contracts/Storage.sol
test/Storage.test.js

- check that starting a contract is only allowed when the corresponding offer has been selected by the client
- check that finishing a contract is only allowed if it's been started in the first place

Fix start/finish contract

---

contracts/Proofs.sol
contracts/Storage.sol
contracts/TestProofs.sol
test/Proofs.test.js
test/evm.js

Adds a function `willProofBeRequired()` which checks whether a proof will soon be required. When [pointer is in downtime][1], but still points to a blockhash that requires a proof to be submitted, then this function will return true. Together with the pointer position, this allows a host to determine whether or not it makes sense to produce a proof for the current period.
[1]: https://github.com/status-im/dagger-research/blob/main/design/storage-proof-timing.md#pointer-downtime

Check whether proof will be required soon

---

contracts/Proofs.sol
contracts/Storage.sol
contracts/TestProofs.sol
test/Marketplace.test.js
test/Proofs.test.js

Emit an event containing the proof when it's submitted.
This allows a validator to listen for submitted proofs.

Submit proof event

---

Readme.md
contracts/Marketplace.sol
contracts/Storage.sol
test/Marketplace.test.js
test/Storage.test.js
test/examples.js
test/ids.js

Remove the negotiation steps whereby a host submits an offer and a client selects an offer. Start the contract with the host that submits the first proof of storage.
A first step towards the design in https://github.com/status-im/codex-research/pull/83.

Start contract on proof submission

---

contracts/Marketplace.sol
contracts/Storage.sol

Change the names of some bytes32 parameters to `slotId` and `requestId` to avoid confusion.

[chore] clean up bytes32 parameters

---

contracts/AccountLocks.sol
contracts/Marketplace.sol
contracts/Storage.sol
contracts/TestAccountLocks.sol
contracts/TestMarketplace.sol
test/AccountLocks.test.js
test/Marketplace.test.js
test/Storage.test.js
test/marketplace.js

Once a storage request is created by the client, if all the slots are filled before the expiry lapses, the request state of the contract is set to `RequestState.Started`. The lock expiry (that prevents client funds withdrawal) is also extended.
If the expiry lapses before all slots are filled, the request state is considered cancelled, however the state cannot be automatically updated. At this point, the functions `isCancelled` and `isSlotCancelled` will return true. Also at this point, the client can withdraw its funds from the contract, and in that transaction, the request state of the contract is set to `RequestState.Cancelled`.
Proofs cannot be marked as missing when `isSlotCancelled` is true. This is the point at which a storage request's expiry lapsed before all slots were filled. …

[marketplace] Add request state and add/remove slot proving based on state

---

contracts/AccountLocks.sol
contracts/Marketplace.sol
contracts/Proofs.sol
contracts/Storage.sol
contracts/TestAccountLocks.sol
contracts/TestCollateral.sol
contracts/TestMarketplace.sol
contracts/TestProofs.sol
hardhat.config.js

`RequestId`, `SlotId`, `LockId`, `ProofId`, `EndId` types were created to avoid confusion and enforce compiler restrictions.
Closes #21.
This is based off of #19, so probably should look at merging that first, then rebase this PR on top of main.

[marketplace] alias bytes32 types

---

contracts/Marketplace.sol
test/Marketplace.test.js
test/Storage.test.js
test/marketplace.js

Maintains a list of active requests per client.
This can be used by the codex node to restore its state when restarted.
Uses an EnumerableSet from OpenZeppelin to ensure that adding and removing from the list is O(1).
Depends on the changes from #20; it needs to be merged first.

List of active requests

---

contracts/Marketplace.sol
contracts/Proofs.sol
contracts/TestProofs.sol
test/Proofs.test.js

Proofs should be required from the moment a slot is filled, not from the moment a request is submitted.
Reverts part of #28.

Fix: use slot start instead of request start

---

contracts/Marketplace.sol
test/Marketplace.test.js
test/requests.js

- Add public function to get request from slot id.
- Add chai test assertion that compares requests. Usage: `expect(await marketplace.getRequestFromSlotId(slotId(slot))).to.be.request(request)`
This is used when restoring active sale: a node calls `mySlots`, returning an array of `SlotIds`, which are then iterated  to get the originating request details from the contract.

get request from slot id

---

hardhat.config.js

- stop on first failure (quick feedback)
- do not warn about slow test before 100 ms (solidity tests are inherently slow)
- set test timeout to 30 seconds
- ~~run tests in parallel in CI~~ (did not make CI faster)

Tweak test settings

---

contracts/Marketplace.sol
contracts/Proofs.sol
test/Marketplace.test.js

When a slot is freed after the host misses too many proofs, the "missed proofs counter" is not reset, and hence the new host that fills the freed slot will have a non-zero "missed proofs counter". While this does not impact functionality as the logic uses modulo in the implementation, if somebody queries the `missingProofs()` method directly, he would be surprised with the number he would potentially get.

fix: reset missed counter when slot is freed

---

contracts/Marketplace.sol
test/Marketplace.test.js

Store slotIndex in slot struct and expose the slot via getActiveSlot. This is to be used when restoring state in the sales module after a node restart.

retrieve active slot for sales state restoration

---

deploy/marketplace.js

Needed for https://github.com/status-im/nim-codex/issues/372
It is not needed per-se as it seems that the address should be deterministic, but if there would be a case when we add a transaction into the deployment script, then the address would change, so this is just a safe guard to make it future-proof.

build: make sure marketplace is on predefined address

---

.github/workflows/ci.yml
.gitignore
Readme.md
contracts/FuzzMarketplace.sol
contracts/Marketplace.sol
contracts/Proofs.sol
fuzzing/corpus/.gitignore
fuzzing/echidna.yaml
fuzzing/fuzz.sh
package.json
test/Marketplace.test.js

Simplifies the contract code by moving the invariant checks to separate files.
Uses [echidna](https://github.com/crytic/echidna) to perform the fuzzing.

Use fuzzing to check invariants

---

.github/workflows/docker-dist-tests.yml
docker/deploy.Dockerfile

This PR adds Docker builds which are [required by Dist-Tests](https://github.com/codex-storage/cs-codex-dist-tests/issues/34). It is done besides recently added [Add Docker builds #56](56) and we will store images in different DockerHub repositories
- [codexstorage/codex-contracts-eth](https://hub.docker.com/r/codexstorage/codex-contracts-eth/tags)
- [codexstorage/dist-tests-codex-contracts-eth](https://hub.docker.com/r/codexstorage/dist-tests-codex-contracts-eth/tags)
These builds has slightly different behaviour and we probably would like how have both of them.
Also, it was required to update existing [docker/deploy.Dockerfile](https://github.com/codex-storage/codex-contracts-eth/blob/master/docker/deploy.Dockerfile) because
1. Builds on ARM failed without additional packages …

Add Docker builds for Dist-Tests

---

docker/Dockerfile

We [recently updated Hardhat and Node](64) to the lates versions.
Because both dockerfiles uses same source code it make sense to update main Dockerfile to use same Node version.

chore: Bump Node version

---

contracts/Requests.sol
test/examples.js
test/ids.js

Update Request to accomodate new proving scheme:
- Remove PoR parameters
- Remove total number of chunks
- Add merkle root of the dataset

Remove PoR parameters, add merkle root for storage proofs

---

contracts/Marketplace.sol
test/Marketplace.test.js

During some manual testing, I ran into a case when I accidentally specified the expiry to be farther than the request's end. This led to underflow errors due to the calculation of the `expiryFundsWithdraw` during the `fillSlot()` event. This is a fix that prevents this condition.
In the `nim-codex` follow-up PR, I will also add a check for this on the API level.

fix: check expiration is before request end

---

contracts/Proofs.sol

In order to prevent the pointer from being in downtime through many consecutive periods (up to 64 blocks, or just over 6 periods), the pointer is increased by 64 blocks each time the period is increased.
Based on https://github.com/codex-storage/codex-contracts-eth/pull/78

Increase pointer by 67 blocks each time the period is increased

---

contracts/TestVerifier.sol
deploy/marketplace.js
deploy/token.js
deploy/verifier.js
test/Marketplace.test.js
test/Proofs.test.js
test/examples.js

Deploy 2 versions of the marketplace (only on local network):
- Marketplace with Groth16 Verifier
- Marketplace with TestVerifier
The test verifier accepts all proofs, except when it has all 0 values. 
Necessary for testing the codex client, until we can generate real ZK proofs.
Removes the code that deploys contracts to a fixed address, because it doesn't seem to work, and I couldn't find a way to get it to work.

Dummy verifier

---

contracts/FuzzMarketplace.sol
contracts/Marketplace.sol

Implicit getters have slightly different semantics when it comes to ABI encoding their results.
This lead to a problem when calling the getter for the config that contains the zkeyHash string.
The decoding problem has been solved in https://github.com/codex-storage/nim-ethers/pull/63, but that is not ready to be merged yet, because it depends on the chronos v4 changes in nim-ethers.
This is a workaround that makes the getters explicit.

Explicit getters for token and config

---

deploy/marketplace.js

In Codex's integration tests we now create real ZK proofs, which take a bit longer to generate. We therefore need a period that remains the same while the proof is generated.

Increase proof period

---

contracts/Groth16.sol
contracts/Groth16Verifier.sol
contracts/TestVerifier.sol
verifier/verifier.js

Reason: Circom and Ethereum EIP-197 both represent these elements as arrays of two elements, but they do it in reverse order of each other. This change makes it explicit which number is the real part, and which number is the imaginary part.

Verifier: represent elements from field F_{p^2} as `real + i * imag`

---

deploy/marketplace.js

This makes it faster to test these scenarios in the codex integration tests.
(These configuration parameters are now specialized for our integration tests.
Pretty soon we'll probably want to have different configurations for distributed
testing, our testnet, etc. But that's something for another PR)

Slash and free slot sooner when proofs are missed

---

contracts/Groth16.sol
contracts/Groth16Verifier.sol
test/Proofs.test.js

Refactors the Groth16 verifier to:
- fix mistakes
- remove unnecessary conversions
- make it more readable
- return false instead of stopping execution when an operation fails

Refactor of the solidity Groth16 verifier

---

.github/workflows/ci.yml
.github/workflows/docker-reusable.yml

This is similar to https://github.com/codex-storage/nim-codex/pull/712 and to eliminate node16 deprecation warnings.
Since syntax in v4 upload/download-artifact was slightly changed, workflow was adjusted similar to [`nim-codex/.github/workflows/docker-reusable.yml`](https://github.com/codex-storage/nim-codex/tree/master/.github/workflows/docker-reusable.yml).

ci: update actions to the latest major versions

---

.github/workflows/ci.yml

This PR is to save resources and add some order using [concurrency](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/using-concurrency). On Push/Pull request, previously running job will be canceled as [we do it for nim-codex](https://github.com/codex-storage/nim-codex/blob/4f56f2af26d77af1490ef499d487aad965ff70bf/.github/workflows/ci.yml#L15-L17)
We also updated actions to the latest releases to remove deprecation warnings

ci: add ci job concurrency

---

contracts/Marketplace.sol
test/Marketplace.test.js

`request.ask.maxSlotLoss` has to be less or equal to `slots`. This check was missing, so this commit adds it and provdes a test to confirm this as well.
Fixes #139

fix: ensure requestStorage() reverts if maxSlotloss > slots

---

.github/workflows/ci.yml

This updates `certora-cli` to the latest version (at the time of the commit, this was 7.10.1).

chore(ci): update certora-cli version in CI tasks

---

certora/harness/MarketplaceHarness.sol
certora/specs/Marketplace.spec

This invariant verifies that any given proof cannot be marked as missing if the slot period has not passed yet.
**This PR sits on top of #147**

chore(certora): add invariant that proofs cant be missing when in period

---

certora/specs/Marketplace.spec
contracts/Proofs.sol

This invariant makes sure that `_missed[slotId]` is equal to the count of `_missing[slotId]` periods set to `true`.
Closes #133

chore(certora): slot's missed periods count should be equal to the count of slot's missing periods set to true

---

certora/specs/Marketplace.spec
contracts/Marketplace.sol
test/Marketplace.test.js
test/marketplace.js

Closes: #71.
Adds an optional `payoutAddress` to the `fillSlot` function, tracking this address in the `Slot`. When SPs are paid out after request completion/cancellation, reward payouts are paid to the `payoutAddress` (if supplied), while collateral is returned to the SP's address. If the `payoutAddress` is not supplied in `fillSlot`, payouts are made to the SP's address (as it was before this PR).

feat: adds an optional `payoutAddress` to allow payouts to be paid to separate address

---

certora/confs/Marketplace.conf

Fixes the certora config to use the MarketplaceHarness as parameteric config value

set MarketplaceHarness as parametric_contract config value

---

certora/harness/MarketplaceHarness.sol
certora/specs/Marketplace.spec
contracts/Marketplace.sol

We've had a bug in our certora configuration which resulted in may of our rules to pass, which are actually failing, now that the configuration has been updated.
This PR introduces a bunch of commits that in aggregate fix the broken rules again.
Closes #161

Make certora rules pass again

---

.github/workflows/ci.yml
certora/specs/Marketplace.spec

This should fix the bug of certora-cli not properly completing with non zero exit codes on errors, which ultimately results in CI tasks to give false positives.

chore(CI): update certora-cli to 7.10.2

---

contracts/Marketplace.sol
test/Marketplace.test.js

There is a missing check in `requestStorage()` on whether the `Request` contains an `Ask` where its `slots` is `> 0`.
This allows for making storage request without slots. Not harmful but not a valid state of the system either.
This commit adds that check and a test with batteries included.

fix(Marketplace): ensure requests include ask with sufficient slots

---

certora/specs/Marketplace.spec

`paidSlotAlwaysHasCancelledOrFinishedRequest`
The mentioned invariant uses a `preserved` block with a `require SlotState == Paid`, which essentially excludes all cases where `SlotState != Paid`.
This was incorrectly applied. Removing that requirement causes the prover to find a counter example where it starts with `RequestState == Started` and `SlotState == Cancelled`.
This ultimately results in `SlotState == PAID` while `RequestState` stays `Started`.
Counter example link: https://prover.certora.com/output/6199/a38c9bd665d544dabcffd07335c05420?anonymousKey=119a850a4d1d65ccbe8f95298615592835801d2b
A slot that is `Cancelled` however, can never belong to a request that is `Started`. So requiring the invariant that
`cancelledSlotAlwaysHasCancelledRequest` fixes this and the rule is passing. …

fix(certora): remove incorrect requirment in

---

certora/harness/MarketplaceHarness.sol
certora/specs/Marketplace.spec

Instead of having additional harness code in `MarketplaceHarness` to access fields in `requestContext` and `slots` objects, this introduces dedicated ghost variables that keep track of the field changes and let us read the values from there.
Prover run: https://prover.certora.com/output/6199/8343693dfc3f4ca38435f5aa10fa2345?anonymousKey=db5eaee6c688651132d1671919fb73544affa269
Closes #165

refactor(certora): use ghost variables for `requestContext` and `slots`

---

certora/harness/MarketplaceHarness.sol
certora/specs/Marketplace.spec

This PR adds a rule to check the possible slot transitions saved in storage and adss an helper function to check the consistency of the slot attributes.

chore(certora): verify possible slot state transitions

---

contracts/Configuration.sol
contracts/FuzzMarketplace.sol
contracts/Marketplace.sol
contracts/SlotReservations.sol
contracts/TestSlotReservations.sol
deploy/marketplace.js
test/SlotReservations.test.js
test/examples.js

Closes #175. 
These functions are not called yet. They are being implemented as part of a [longer list of tasks for slot reservations](https://github.com/codex-storage/codex-pm/issues/45) to prevent PRs from being too large.
Allows reservation of slots, without an implementation of the expanding window.
- Add a function called `reserveSlot(address, SlotId)`, that allows three unique addresses per slot to be reserved. 
- Revert if reservations full or if provider address already reserved slot
- Use `mapping(SlotId => EnumerableSet.AddressSet)`
- Add `canReserveSlot(address, SlotId)`
- Return `true` if set of reservations is less than 3 and the set doesn't already contain the address
- Return `true` otherwise (for now, later add in logic for checking the address is inside the expanding …

feat(slot-reservations): Allow slots to be reserved

---

contracts/SlotReservations.sol
test/SlotReservations.test.js

Closes #182.
This is being implemented as part of a [longer list of tasks for slot reservations](https://github.com/codex-storage/codex-pm/issues/45) to prevent PRs from being too large.
When the number of reservations for a slot reaches `config._MAX_RESERVATIONS`, a `SlotReservationsFull` event is emitted with the `RequestId` and `slotIndex` of the slot.

feat(slot-reservations): Add `SlotReservationsFull` event

---

contracts/Marketplace.sol
test/Marketplace.test.js
test/marketplace.js

Closes #184.
This is being implemented as part of a [longer list of tasks for slot reservations](https://github.com/codex-storage/codex-pm/issues/45) to prevent PRs from being too large.
Requires that a slot is reserved before slot is allowed to be filled.

feat(slot-reservations): require slots to be reserved before filling slot

---

certora/specs/Marketplace.spec
contracts/Marketplace.sol
contracts/Requests.sol
test/Marketplace.test.js
test/marketplace.js
test/price.js
test/requests.js

This PR bundles few changes around payout and withdraws:
- Hosts are paid by their actual time hosting the slot (also relevant for repair)
- Client can withdraw remaining funds for finished requests
- Client can withdraw all original funds for failed requests
- When a slot is "forcible freed" and the slot would not be filled again, but the request would successfully finish - client can withdraw the funds for this slot
I am not so happy about the testing because it is pretty hard to correctly calculate the amounts that should be returned due to Hardhat's "auto" mining of blocks every time there is a transaction, which advances the clock and hence shifts the reward calculations. I made it work, but not great. My brain is fried though, so I will leave it for now and check back on it …

feat: hosts payed by actual time hosting a slot

---

contracts/Marketplace.sol

This is not the right reason to be making this kind of change, but a very hard to debug symbol clash in codex for `config`. Changing this to `configuration` is the easiest way to fix the issue.
I spent nearly an entire day unsuccessfully trying to solve a strange symbol clash with `config` inside the integration tests. This was a last resort, and it works. Alternative attempts to solve the clash are welcome.
This is part of the getting the latest ethers merged into codex (to fix the nonce issue plaguing the testnet).

renames config to configuration

---

contracts/Marketplace.sol
contracts/SlotReservations.sol
contracts/TestSlotReservations.sol
test/SlotReservations.test.js

Ensure that the slot state is free before allowing reservations

fix(slot-reservations): ensure slot is free

---

configuration/networks/hardhat/configuration.js

Reason: on windows, the nim-codex integration tests run so slow that they cannot fill a slot within 60 seconds.
Slowness is most likely caused by https://github.com/codex-storage/nim-ethers/issues/95.

Increase proof period to 90 seconds on hardhat network

---

.github/workflows/ci.yml

Tweaks the CI trigger limiting "push" trigger only to `master` and also configures to checkout the true PR branch.

ci: tweaks run triggers and checkout hash

---

certora/specs/Marketplace.spec
contracts/Configuration.sol
contracts/Marketplace.sol
contracts/Requests.sol
test/Marketplace.test.js
test/requests.js

Closes #154 
The reward is attributed using a discount provided for the collateral required to be deposited. In this way, the reward is actually paid out at the end of Storage Request where the full amount of collateral is returned (provided no slashing occurred).

feat: repair reward

---

configuration/configuration.js
contracts/Configuration.sol
contracts/FuzzMarketplace.sol
contracts/Marketplace.sol
test/Marketplace.test.js
test/examples.js

Reward validator when marking missing proof

---

certora/harness/MarketplaceHarness.sol
certora/specs/Marketplace.spec
configuration/configuration.js
configuration/networks/hardhat/configuration.js
contracts/Configuration.sol
contracts/FuzzMarketplace.sol
contracts/Marketplace.sol
contracts/Periods.sol
contracts/Proofs.sol
contracts/Requests.sol
contracts/SlotReservations.sol
test/examples.js
test/ids.js

I ran into yet another instance where we were using `uint256` for a time interval (duration, expiry, etc.), which does not make sense and makes working with these parameters in nim-codex more annoying, so my patience ran out, and I scaled down all the time relevant params to `uint64`. And since I was at it, I also started to look into others like `slotSize` and `slots`. I scaled those to `uint64` as well. The `slots` (eq. number of slots in storage request) is IMHO fine having `uint64`, but the `slotSize` gives us 16 exabytes, which is IMHO also fairly alright. 
I would like to point out, that with these changes and the reshuffling of the order in `Ask` we are saving 3x `uint256`, as the 4*`uint64` will fit into one "word" (eq. `uint256`).
Let me know what you think about these changes …

perf: optimizing parameters sizing

---

contracts/Marketplace.sol
hardhat.config.js
test/Marketplace.test.js
test/Proofs.test.js
test/evm.js
test/marketplace.js

- use the `allowBlocksWithSameTimestamp` hardhat option
- remove block time gymnastics from marketplace tests
- fix erroneous implementation of requestEnd() which surfaced because of the the improved tests

simplify time-based logic in tests, and fix requestEnd()

---

contracts/Marketplace.sol
contracts/SlotReservations.sol
contracts/TestSlotReservations.sol
package-lock.json
package.json
test/Marketplace.test.js
test/SlotReservations.test.js

Deleting an AddressSet causes corrupted memory. Each address must be removed individually, which is OK to do since there is a maxReservations parameter that keeps this number small.
https://docs.openzeppelin.com/contracts/5.x/api/utils#EnumerableSet

fix(slot reservations): clear AddressSet instead of delete

---

contracts/Marketplace.sol
contracts/Proofs.sol

This PR fixes https://github.com/codex-storage/nim-codex/issues/1153 by adding a new function in the contract, `canProofBeMarkedAsMissing`.
Since this function is a view and does not transfer reward funds to the validator, we should no longer encounter the `ERC20: transfer to the zero address` error.
Moreover, it updates the contracts since the `requestEnd` has been fixed in the contracts.

chore: add a new canMarkProofAsMissing function

---

docker/Dockerfile
docker/deploy.Dockerfile

We should use `npm ci` over `npm install` as `ci` uses lock file for installing deps, while `install` can bump the deps versions.

build: docker uses npm ci

---

contracts/Marketplace.sol

Hardhat has a known issue where custom error selectors are not able to be parsed from the stack trace when there is a revert inside of a modifier. Instead, reverting inline in the function does have present have the same issue in hardhat. 
This is a workaround for an issue in hardhat which is not the best reason to create a patch, however, we need to move forward with work in codex, and this is blocking us.

fix(integration): fixes hardhat not recognising custom error

---

configuration/networks/codexdisttestnetwork/configuration.js

There's an issue in the tests that is caused by misconfigured marketplace deployment, because the block frequency is different. This is a step towards fixing these tests by allowing the tests to set the marketplace configuration values.

Adds env-var configurable configuration
